sudo: required
dist: trusty
language: csharp
solution: src/Cmsql.sln
addons:
  apt:
    packages:
      - oracle-java8-set-default
before_install:
  - sudo mkdir /etc/mono/registry
  - sudo chmod uog+rw /etc/mono/registry
install:
  - nuget restore src/Cmsql.sln
  - nuget install xunit.runner.console -Version 2.3.1 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release src/Cmsql.sln
  - mono ./testrunner/xunit.runner.console.2.3.1/tools/net452/xunit.console.exe ./src/Cmsql.Test/bin/Release/Cmsql.Test.dll
  - mono ./testrunner/xunit.runner.console.2.3.1/tools/net452/xunit.console.exe ./src/Cmsql.Grammar.Test/bin/Release/Cmsql.Grammar.Test.dll