sudo: required
dist: trusty
language: csharp
solution: src/Cmsql.sln
before_install:
  - sudo add-apt-repository ppa:openjdk-r/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y openjdk-8-jdk
  - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
install:
  - nuget restore src/Cmsql.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release src/Cmsql.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe .src/Cmsql.Test/bin/Release/Cmsql.Test.dll
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe .src/Cmsql.Grammar.Test/bin/Release/Cmsql.Grammar.Test.dll
